# Generated by Django 3.2.5 on 2021-07-16 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.customer')),
                ('items_json', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=4000)),
                ('fname', models.CharField(max_length=90)),
                ('lname', models.CharField(max_length=90)),
                ('amount', models.IntegerField(default=0)),
                ('branch', models.CharField(max_length=90)),
                ('reg_id', models.CharField(max_length=90)),
                ('mobno', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(default='', max_length=1000)),
                ('orderstatus', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=75)),
                ('price', models.IntegerField(default=0)),
                ('tagline', models.CharField(default='', max_length=100)),
                ('desc', models.CharField(default='', max_length=2000)),
                ('sblack', models.IntegerField(default=1)),
                ('mblack', models.IntegerField(default=1)),
                ('lblack', models.IntegerField(default=1)),
                ('xlblack', models.IntegerField(default=1)),
                ('sblue', models.IntegerField(default=1)),
                ('mblue', models.IntegerField(default=1)),
                ('lblue', models.IntegerField(default=1)),
                ('xlblue', models.IntegerField(default=1)),
                ('image', models.ImageField(default='', upload_to='shop/themes/images')),
                ('subimg1', models.ImageField(default='', upload_to='shop/themes/images')),
                ('subimg2', models.ImageField(default='', upload_to='shop/themes/images')),
                ('subimg3', models.ImageField(default='', upload_to='shop/themes/images')),
                ('subimg4', models.ImageField(default='', upload_to='shop/themes/images')),
            ],
        ),
    ]
