# Generated by Django 3.0.4 on 2020-04-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=75)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.CharField(default='', max_length=2000)),
                ('image', models.ImageField(default='', upload_to='shop/themes/images')),
            ],
        ),
    ]
