# Generated by Django 3.2.5 on 2021-07-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items_json',
            field=models.CharField(default='{}', max_length=4000),
        ),
    ]
