# Generated by Django 3.0.4 on 2020-04-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lblack',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='lblue',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='mblack',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='mblue',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='sblack',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='sblue',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='subimg1',
            field=models.ImageField(default='', upload_to='shop/themes/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='subimg2',
            field=models.ImageField(default='', upload_to='shop/themes/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='subimg3',
            field=models.ImageField(default='', upload_to='shop/themes/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='subimg4',
            field=models.ImageField(default='', upload_to='shop/themes/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='xlblack',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='xlblue',
            field=models.IntegerField(default=1),
        ),
    ]
