# Generated by Django 3.0.4 on 2020-04-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200430_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tagline',
            field=models.CharField(default='', max_length=100),
        ),
    ]
