# Generated by Django 3.0.4 on 2020-05-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200503_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='items_json',
            field=models.CharField(default={}, max_length=4000),
            preserve_default=False,
        ),
    ]
