# Generated by Django 3.0.4 on 2020-05-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200503_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
    ]
