# Generated by Django 3.0.4 on 2020-05-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(default='', max_length=1000)),
                ('orderstatus', models.CharField(max_length=1000)),
            ],
        ),
    ]
